######################## Theme configuration ####################
theme = "twenty-twenty-hugo"

[languages]
######################## 繁體中文 default configuration ####################
  [languages.zh]
  baseURL = 'https://aeicafe.com'
    languageName = '繁體中文'
    title = '安迪艾倫咖啡小館'
    weight = 1
    contentDir = './content'


######################## English default configuration ####################
  [languages.en]
  baseURL = 'https://aeicafe.com/en'
    languageName = 'English'
    title = 'Andy Ellen I café'
    weight = 2
    contentDir = './content/en'

######################## Japan default configuration ####################
  [languages.jp]
      baseURL = 'https://aeicafe.com/jp'
      languageName = 'にほんご'
      title = '日本語／にほんご'
      weight = 3
      contentDir = './content/jp'

######################## France default configuration ####################
  [languages.fr]
      baseURL = 'https://aeicafe.com/fr'
      languageName = 'Français'
      title = 'En Français'
      weight = 4
      contentDir = './content/fr'

# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here
# google analytics
googleAnalytics = "" # example : UA-123-45



############################## Output ###############################
[outputs]
home = ["HTML", "RSS", "JSON"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
author = "author"

############################## navigation ###############################


  # main menu
  [[menu.main]]
  name = "首頁"
  URL = "/"
  weight = 1

  [[menu.main]]
  name = "餐點菜單"
  URL = "food-menu"
  weight = 2

  [[menu.main]]
  name = "飲品菜單"
  URL = "drink-menu"
  weight = 3

  [[menu.main]]
  name = "交通資訊"
  URL = "traffic"
  weight = 4

  [[menu.main]]
  name = "聯絡資訊"
  URL = "contact"
  weight = 5


  # only desktop menu
  [[menu.desktop]]
  name = "聯絡資訊"
  URL = "contact"
  weight = 1


    # main menu France
        [[languages.fr.menu.main]]
        name = "fr 首頁 home"
        URL = "/"
        weight = 1

    [[languages.fr.menu.main]]
        name = "cusinè food menu"
        URL = "food-menu"
        weight = 2  

    # blog
        [params.fr.blog]
        heading="餐點 Meals"
        heading2 ="飲品 Drinks"

    [languages.fr.outputs]
        home = ["HTML", "RSS", "JSON"]

    # unsafe html
        [languages.fr.markup.goldmark.renderer]
        unsafe = true

    [languages.fr.taxonomies]
        category = "categories"
        tag = "tags"
        author = "author"

#################### default parameters ################################
[params]
# Meta data
description = "This is aeicafe.com, a cafe website"
author = "Aeicafe"

# favicon
[params.favicon]
favicon = "images/favicon.png"

# cookies
[params.cookies]
enable = false
expire_days = 2
        
# banner
[params.banner]
image = "images/2021-aeicafe-landscape.jpg"

# blog
[params.blog]
heading="餐點 Meals"
heading2 ="飲品 Drinks"

# call to action
[params.call_to_action]
enable = false
title = "Contact us for more information."
picture = "images/traffic.png"
content = "https://g.page/Thtea?share Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis"
button_label = "Contact Us"
button_url = "contact"

# gallery
[params.gallery]
enable = true

[[params.gallery.gallery_item ]]
image = "images/traffic.png"

############################# footers ########################

# footer
[params.footer]
title = "關於我們"
content = "安迪艾倫咖啡小館  Andy Ellen I café"
address = "新北市淡水區北新路117-2號"
hours = "Monday–Friday: 12:00AM–9:00PM <br> Saturday & Sunday: 12:00AM–9:00PM"
copyright = "Copyright &copy; 2022 安迪艾倫咖啡小館 Andy Ellen I café"


# footer zh 
[languages.zh.params.footer]
title = "關於我們"
content = "安迪艾倫咖啡小館  Andy Ellen I café"
address = "新北市淡水區北新路117-2號"
hours = "Monday–Friday: 12:00AM–9:00PM <br> Saturday & Sunday: 12:00AM–9:00PM"
copyright = "Copyright &copy; 2022 安迪艾倫咖啡小館 Andy Ellen I café"

# footer en
[languages.en.params.footer]
title = "About us"
content = "Andy Ellen I café"
address = "No. 117-2, Beixin Rd, Tamsui District, New Taipei City, 251"
hours = "Monday–Friday: 12:00AM–9:00PM <br> Saturday & Sunday: 12:00AM–9:00PM"
copyright = "Copyright &copy; 2022 Andy Ellen I café"

# footer jp
[languages.jp.params.footer]
title = "前書き"
content = " Andy Ellen I café コーヒーショップ"
address = "新北市淡水区北新路117-2号"
hours = "Monday–Friday: 12:00AM–9:00PM <br> Saturday & Sunday: 12:00AM–9:00PM"
copyright = "Copyright &copy; 2022 安迪艾倫咖啡小館 Andy Ellen I café"

# footer fr
[languages.fr.params.footer]
title = "About us"
content = "Andy Ellen I café"
address = "No. 117-2, route Beixin, district de Tamsui, nouvelle ville de Taipei"
hours = "Monday–Friday: 12:00AM–9:00PM <br> Saturday & Sunday: 12:00AM–9:00PM"
copyright = "Copyright &copy; 2022 安迪艾倫咖啡小館 Andy Ellen I café"

############################# social site ########################
[params.social]

facebook = "https://www.facebook.com/aeicafe"
twitter = "#"
instagram = "#"
email = "aeicafe@gmail.com"

